sbatch slurm/run_gpu.sbatch src/hypernetwork/train_stage1.py \
  --checkpoint checkpoints/trained_d2l/gemma_2b_d2l/checkpoint-20000/pytorch_model.bin \
  --dataset hotpotQA_compact \
  --output_dir train_outputs/stage1_hotpotqa_finetune \
  --num_train_epochs 5 \
  --learning_rate 2e-5 \
  --gradient_accumulation_steps 8 \
  --max_packed_inp_len 4096 \
  --max_packed_ctx_len 4096 \
  --logging_steps 10 \
  --bf16 \
  --wandb \
  --ctx_encoder_type per_layer_activations \
  --num_blocks 9 \
  --use_kl_loss \
  --use_per_ctx_average_loss \
  --gen_lora_l1_reg_coef 0.1