sbatch slurm/run_gpu.sbatch src/train_stage1.py \
  --checkpoint checkpoints/trained_d2l/gemma_2b_d2l/checkpoint-20000/pytorch_model.bin \
  --dataset hotpotQA_compact \
  --output_dir train_outputs/stage1_hotpot_finetune \
  --num_train_epochs 5 \
  --learning_rate 2e-5 \
  --gradient_accumulation_steps 8 \
  --max_packed_inp_len 4096 \
  --max_packed_ctx_len 4096 \
  --logging_steps 10 \
  --bf16 \
  --wandb \
  --num_blocks 8