sbatch slurm/run_gpu.sbatch src/train_stage1.py \
  --model_name google/gemma-2-2b-it \
  --dataset hotpotQA_compact \
  --output_dir train_outputs/stage1_hotpot_scratch \
  --num_train_epochs 5 \
  --learning_rate 2e-5 \
  --gradient_accumulation_steps 8 \
  --max_packed_inp_len 4096 \
  --max_packed_ctx_len 4096 \
  --logging_steps 10 \
  --bf16 \
  --wandb \
  --ctx_encoder_type early_exit \
  --num_blocks 8